name: ChaosLoadTesting

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: Azure/login@v1.4.5
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Start Load Test Experiment
      uses: Azure/cli@v1
      with:
        inlineScript: az rest --method post --uri https://management.azure.com/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Chaos/experiments/$EXPERIMENT_NAME/start?api-version=2021-09-15-preview
      env:
        SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        EXPERIMENT_NAME: pod-failure
        RESOURCE_GROUP: global-azure-torino-2023
